server:
  port: 8080
  servlet:
    context-path: ""

spring:
  # RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
  thymeleaf:
    cache: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.75.24:3306/community?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: 654321Byf.
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  mail:
    host: smtp.sina.com
    port: 465
    username: byfgg123@sina.com
    password: 5df3c9d73de3386c
    properties:
      mail:
        smtl:
          auth: true
    protocol: smtps
  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300
  #TaskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    #TaskSchedulingProperties
    scheduling:
      pool:
        size: 5
  # QuartzProperties
  #  spring.quartz.job-store-type=jdbc
  #  spring.quartz.scheduler-name=communityScheduler
  #  spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
  #  spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
  #  spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  #  spring.quartz.properties.org.quartz.jobStore.isClustered=true
  #  spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
  #  spring.quartz.properties.org.quartz.threadPool.threadCount=5
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

  # kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      #自动提交
      enable-auto-commit: true
      auto-commit-interval: 3000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      nowcoder:
        community: debug

community:
  path:
    domain: http://39.101.75.24
    upload: /tmp/uploads

#wk
wk:
  image:
    command: /opt/wkhtmltopdf.sh
    storage: /tmp/wk-images

#qiniu
qiniu:
  key:
    access: lUxBYhWwUDSb87XBoqB0hWpFHx9QjEP5BcBQC5bx
    secret: -mwDYUdt3sF57hYSFRU3LkH9OI0XbqbIpw0tIklm
  bucket:
    header:
      name: communityheaderbyfgg
      url: http://rihw899a9.hd-bkt.clouddn.com
    share:
      name: communitysharebyfgg
      url: http://rihwnc20l.hd-bkt.clouddn.com

#  qiniu.key.access=6RA-Uus95ZT_1znMrCMD8BpqfjT-K7OKmQTfKB48
#  qiniu.key.secret=kPNnLFz2_tzztKUVpSLm0lYngtuHWyIq5LzTmLIL
#  qiniu.bucket.header.name=community_header
#  quniu.bucket.header.url=http://pvghrij81.bkt.clouddn.com
#  qiniu.bucket.share.name=community_share
#  qiniu.bucket.share.url=http://pvghvvuzm.bkt.clouddn.com
#
#caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'



